name: test main
on:
  push:
    branches:
      - main
jobs:

# ROLE TESTS
  apache2:
    runs-on: ubuntu-latest
    env:
      NO_TTY: "1"
    steps:
      - uses: actions/checkout@v3
      - run: .test/test_role.sh apache2 -vvv

  elasticsearch:
    runs-on: ubuntu-latest
    env:
      NO_TTY: "1"
    steps:
      - uses: actions/checkout@v3
      - run: .test/test_role.sh elasticsearch -vvv

  files:
    runs-on: ubuntu-latest
    env:
      NO_TTY: "1"
    steps:
      - uses: actions/checkout@v3
      - run: .test/test_role.sh files -vvv

  java:
    runs-on: ubuntu-latest
    env:
      NO_TTY: "1"
    steps:
      - uses: actions/checkout@v3
      - run: .test/test_role.sh java -vvv

  minimal_root_setup:
    runs-on: ubuntu-latest
    env:
      NO_TTY: "1"
    steps:
      - uses: actions/checkout@v3
      - run: .test/test_role.sh minimal_root_setup -vvv

  postgresql:
    runs-on: ubuntu-latest
    env:
      NO_TTY: "1"
    steps:
      - uses: actions/checkout@v3
      - run: .test/test_role.sh postgresql -vvv

  tomcat:
    runs-on: ubuntu-latest
    env:
      NO_TTY: "1"
    steps:
      - uses: actions/checkout@v3
      - run: .test/test_role.sh tomcat -vvv

# CUSTOM TESTS
  tomcat_apache2:
    runs-on: ubuntu-latest
    env:
      NO_TTY: "1"
    steps:
      - uses: actions/checkout@v3
      - run: .test/tomcat_apache2/test.sh -vvv

